name: Code Review and Link Detection



on:

 Â push:

 Â Â Â branches: [ main, master, develop ]

 Â pull_request:

 Â Â Â branches: [ main, master, develop ]

 Â workflow_dispatch:



jobs:

 Â code-review:

 Â Â Â runs-on: ubuntu-latest

 Â Â  

 Â Â Â steps:

 Â Â Â - name: Checkout code

 Â Â Â Â Â uses: actions/checkout@v4

 Â Â Â Â Â with:

 Â Â Â Â Â Â Â fetch-depth: 0



 Â Â Â - name: Find all links in codebase

 Â Â Â Â Â id: find-links

 Â Â Â Â Â run: |

 Â Â Â Â Â Â Â echo "## ðŸ” Found Links in Codebase" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â echo "" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â  

 Â Â Â Â Â Â Â # Find HTTP/HTTPS/www links in all files

 Â Â Â Â Â Â Â echo "### HTTP/HTTPS Links:" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â grep -r -n -E "https?://[^\s\"'<>]+" . --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.github || echo "No HTTP/HTTPS links found" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â  

 Â Â Â Â Â Â Â echo "" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â echo "### WWW Links:" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â grep -r -n -E "www\.[^\s\"'<>]+" . --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.github || echo "No www links found" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â  

 Â Â Â Â Â Â Â # Create detailed report

 Â Â Â Â Â Â Â echo "## ðŸ“Š Detailed Link Analysis" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â echo "" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â  

 Â Â Â Â Â Â Â # Count total links

 Â Â Â Â Â Â Â TOTAL_HTTP=$(grep -r -E "https?://[^\s\"'<>]+" . --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.github | wc -l || echo "0")

 Â Â Â Â Â Â Â TOTAL_WWW=$(grep -r -E "www\.[^\s\"'<>]+" . --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.github | wc -l || echo "0")

 Â Â Â Â Â Â  

 Â Â Â Â Â Â Â echo "- **Total HTTP/HTTPS links found:** $TOTAL_HTTP" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â echo "- **Total WWW links found:** $TOTAL_WWW" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â echo "- **Total links:** $((TOTAL_HTTP + TOTAL_WWW))" >> $GITHUB_STEP_SUMMARY



 Â Â Â - name: Code Quality Check

 Â Â Â Â Â run: |

 Â Â Â Â Â Â Â echo "" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â echo "## ðŸ§ª Code Quality Metrics" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â echo "" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â  

 Â Â Â Â Â Â Â # Basic code metrics

 Â Â Â Â Â Â Â TOTAL_FILES=$(find . -type f -name "*.py" -o -name "*.js" -o -name "*.ts" -o -name "*.java" -o -name "*.cpp" -o -name "*.c" -o -name "*.cs" -o -name "*.go" -o -name "*.rs" | grep -v node_modules | grep -v .git | wc -l)

 Â Â Â Â Â Â Â TOTAL_LINES=$(find . -type f -name "*.py" -o -name "*.js" -o -name "*.ts" -o -name "*.java" -o -name "*.cpp" -o -name "*.c" -o -name "*.cs" -o -name "*.go" -o -name "*.rs" | grep -v node_modules | grep -v .git | xargs wc -l | tail -1 | awk '{print $1}' || echo "0")

 Â Â Â Â Â Â  

 Â Â Â Â Â Â Â echo "- **Code files found:** $TOTAL_FILES" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â echo "- **Total lines of code:** $TOTAL_LINES" >> $GITHUB_STEP_SUMMARY



 Â Â Â - name: Security Scan for Suspicious Links

 Â Â Â Â Â run: |

 Â Â Â Â Â Â Â echo "" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â echo "## ðŸ›¡ï¸ Security Review" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â echo "" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â  

 Â Â Â Â Â Â Â # Check for potentially suspicious domains or patterns

 Â Â Â Â Â Â Â SUSPICIOUS_PATTERNS=(

 Â Â Â Â Â Â Â Â Â "bit\.ly"

 Â Â Â Â Â Â Â Â Â "tinyurl"

 Â Â Â Â Â Â Â Â Â "t\.co"

 Â Â Â Â Â Â Â Â Â "localhost:[0-9]+"

 Â Â Â Â Â Â Â Â Â "127\.0\.0\.1"

 Â Â Â Â Â Â Â Â Â "192\.168\."

 Â Â Â Â Â Â Â Â Â "10\.[0-9]+\.[0-9]+\.[0-9]+"

 Â Â Â Â Â Â Â )

 Â Â Â Â Â Â  

 Â Â Â Â Â Â Â for pattern in "${SUSPICIOUS_PATTERNS[@]}"; do

 Â Â Â Â Â Â Â Â Â MATCHES=$(grep -r -E "$pattern" . --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.github | wc -l || echo "0")

 Â Â Â Â Â Â Â Â Â if [ "$MATCHES" -gt 0 ]; then

 Â Â Â Â Â Â Â Â Â Â Â echo "âš ï¸ Found $MATCHES matches for pattern: $pattern" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â Â Â Â Â grep -r -n -E "$pattern" . --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.github >> $GITHUB_STEP_SUMMARY || true

 Â Â Â Â Â Â Â Â Â fi

 Â Â Â Â Â Â Â done



 Â Â Â - name: Generate Link Report

 Â Â Â Â Â run: |

 Â Â Â Â Â Â Â # Create a detailed CSV report

 Â Â Â Â Â Â Â echo "File,Line,Link,Type" > links_report.csv

 Â Â Â Â Â Â  

 Â Â Â Â Â Â Â # Add HTTP/HTTPS links

 Â Â Â Â Â Â Â grep -r -n -E "https?://[^\s\"'<>]+" . --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.github | while IFS=: read -r file line content; do

 Â Â Â Â Â Â Â Â Â link=$(echo "$content" | grep -oE "https?://[^\s\"'<>]+")

 Â Â Â Â Â Â Â Â Â echo "$file,$line,$link,HTTP/HTTPS" >> links_report.csv

 Â Â Â Â Â Â Â done || true

 Â Â Â Â Â Â  

 Â Â Â Â Â Â Â # Add WWW links

 Â Â Â Â Â Â Â grep -r -n -E "www\.[^\s\"'<>]+" . --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.github | while IFS=: read -r file line content; do

 Â Â Â Â Â Â Â Â Â link=$(echo "$content" | grep -oE "www\.[^\s\"'<>]+")

 Â Â Â Â Â Â Â Â Â echo "$file,$line,$link,WWW" >> links_report.csv

 Â Â Â Â Â Â Â done || true

 Â Â Â Â Â Â  

 Â Â Â Â Â Â Â echo "" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â echo "## ðŸ“‹ Export Options" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â echo "" >> $GITHUB_STEP_SUMMARY

 Â Â Â Â Â Â Â echo "A detailed CSV report has been generated as an artifact." >> $GITHUB_STEP_SUMMARY



 Â Â Â - name: Upload Links Report

 Â Â Â Â Â uses: actions/upload-artifact@v4

 Â Â Â Â Â with:

 Â Â Â Â Â Â Â name: links-report

 Â Â Â Â Â Â Â path: links_report.csv

 Â Â Â Â Â Â Â retention-days: 30



 Â Â Â - name: Comment on PR (if applicable)

 Â Â Â Â Â if: github.event_name == 'pull_request'

 Â Â Â Â Â uses: actions/github-script@v7

 Â Â Â Â Â with:

 Â Â Â Â Â Â Â script: |

 Â Â Â Â Â Â Â Â Â const fs = require('fs');

 Â Â Â Â Â Â Â Â  

 Â Â Â Â Â Â Â Â Â // Read the CSV file and create a summary

 Â Â Â Â Â Â Â Â Â let summary = "## ðŸ”— Link Detection Report\n\n";

 Â Â Â Â Â Â Â Â  

 Â Â Â Â Â Â Â Â Â try {

 Â Â Â Â Â Â Â Â Â Â Â const csvContent = fs.readFileSync('links_report.csv', 'utf8');

 Â Â Â Â Â Â Â Â Â Â Â const lines = csvContent.split('\n').filter(line => line.trim() !== '');

 Â Â Â Â Â Â Â Â Â Â  

 Â Â Â Â Â Â Â Â Â Â Â if (lines.length > 1) {

 Â Â Â Â Â Â Â Â Â Â Â Â Â summary += `Found ${lines.length - 1} links in the codebase.\n\n`;

 Â Â Â Â Â Â Â Â Â Â Â Â Â summary += "### Sample Links:\n";

 Â Â Â Â Â Â Â Â Â Â Â Â  

 Â Â Â Â Â Â Â Â Â Â Â Â Â // Show first 10 links as examples

 Â Â Â Â Â Â Â Â Â Â Â Â Â for (let i = 1; i < Math.min(11, lines.length); i++) {

 Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â const [file, line, link, type] = lines[i].split(',');

 Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â summary += `- \`${file}:${line}\` - ${link} (${type})\n`;

 Â Â Â Â Â Â Â Â Â Â Â Â Â }

 Â Â Â Â Â Â Â Â Â Â Â Â  

 Â Â Â Â Â Â Â Â Â Â Â Â Â if (lines.length > 11) {

 Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â summary += `\n... and ${lines.length - 11} more links. Download the full report from the Actions artifacts.`;

 Â Â Â Â Â Â Â Â Â Â Â Â Â }

 Â Â Â Â Â Â Â Â Â Â Â } else {

 Â Â Â Â Â Â Â Â Â Â Â Â Â summary += "No links found in the codebase.";

 Â Â Â Â Â Â Â Â Â Â Â }

 Â Â Â Â Â Â Â Â Â } catch (error) {

 Â Â Â Â Â Â Â Â Â Â Â summary += "Error generating report summary.";

 Â Â Â Â Â Â Â Â Â }

 Â Â Â Â Â Â Â Â  

github.rest.issues.createComment({

 Â Â Â Â Â Â Â Â Â Â Â issue_number: context.issue.number,

 Â Â Â Â Â Â Â Â Â Â Â owner: context.repo.owner,

 Â Â Â Â Â Â Â Â Â Â Â repo: context.repo.repo,

 Â Â Â Â Â Â Â Â Â Â Â body: summary

 Â Â Â Â Â Â Â Â Â });
